language: php
sudo: false
addons:
  apt_packages:
  - graphviz
php:
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
before_script:
- composer selfupdate --quiet
- composer install --prefer-dist --no-interaction --no-progress
script:
- make test
before_deploy:
- make build
deploy:
  provider: bintray
  file: artifacts/bintray.json
  user: "halleck45"
  key:
    secure: Pa7uB1ePY9bYKGHovrdC/F2HlrjXGapKTp6McAFcnIksvuwu06Xug0BszqQeUSzKX/y1kivC7ksIp6kI3icHv0cm6K0MvAi+PLxplqtwLsKJPtwoxX5L6r0VOQ8uNaNU2K7+9Gb/5WNov7SfESXpyxOmUUj/QwwnRkj2RqlL9rg=
  on:
    branch: version2_ast
    php: '5.6'
  skip_cleanup: true
